//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarinLend.Common.LocalizationResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZarinLend.Common.LocalizationResource.ResourceFile", typeof(ResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات حساب کاربری.
        /// </summary>
        public static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما غیر فعال می باشد،لطفا با مدیر سایت تماس بگیرید!.
        /// </summary>
        public static string AccountIsDisable {
            get {
                return ResourceManager.GetString("AccountIsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب بن باید 13 رقمی باشد.
        /// </summary>
        public static string AccountNumberMessage {
            get {
                return ResourceManager.GetString("AccountNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار در دسترس.
        /// </summary>
        public static string ActiveBalance {
            get {
                return ResourceManager.GetString("ActiveBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر محل سکونت.
        /// </summary>
        public static string AddressCityName {
            get {
                return ResourceManager.GetString("AddressCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجاره نامه یا سند مالکیت.
        /// </summary>
        public static string AddressDocument {
            get {
                return ResourceManager.GetString("AddressDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان محل سکونت.
        /// </summary>
        public static string AddressProvinceName {
            get {
                return ResourceManager.GetString("AddressProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ شارژ(ريال ایران).
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی.
        /// </summary>
        public static string AmountRequest {
            get {
                return ResourceManager.GetString("AmountRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوست(ها).
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت باید با فرمت صحیح &lt;spna style=&quot;direction: ltr;unicode-bidi: embed;&quot;&gt;6362-14__-____-____&lt;/span&gt; وارد شود.
        /// </summary>
        public static string AyandehBankCardNumberWithDashMessage {
            get {
                return ResourceManager.GetString("AyandehBankCardNumberWithDashMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شماره حساب.
        /// </summary>
        public static string BankAndAccountInfo {
            get {
                return ResourceManager.GetString("BankAndAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک صادر کننده کارت.
        /// </summary>
        public static string BankCardType {
            get {
                return ResourceManager.GetString("BankCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصاویر شناسنامه.
        /// </summary>
        public static string BirthCertificate {
            get {
                return ResourceManager.GetString("BirthCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر توضیحات شناسنامه.
        /// </summary>
        public static string birthCertificateDescription {
            get {
                return ResourceManager.GetString("birthCertificateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -تصویر صفحه اول شناسنامه را بارگذاری کنید&lt;br/&gt;
        ///-حجم فایل بارگذاری شده نباید بیشتر از 1 مگابایت باشد&lt;br/&gt;
        ///-تمام مشخصات روی تصویر باید با اطلاعات هویتی که در هنگام ثبت نام وارد کرده اید،یکسان باشد&lt;br/&gt;
        ///-مشخصات روی تصویر باید خوانا باشد.
        /// </summary>
        public static string BirthCertificatePage1_Info {
            get {
                return ResourceManager.GetString("BirthCertificatePage1_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر صفحه دوم شناسنامه.
        /// </summary>
        public static string BirthCertificatePage2 {
            get {
                return ResourceManager.GetString("BirthCertificatePage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -تصویر صفحه دوم شناسنامه را بارگذاری کنید&lt;br/&gt;
        ///-حجم فایل بارگذاری شده نباید بیشتر از 1 مگابایت باشد&lt;br/&gt;
        ///-مشخصات روی تصویر باید خوانا باشد.
        /// </summary>
        public static string BirthCertificatePage2_Info {
            get {
                return ResourceManager.GetString("BirthCertificatePage2_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال شناسنامه.
        /// </summary>
        public static string BirthCertificateSerial {
            get {
                return ResourceManager.GetString("BirthCertificateSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال شناسنامه.
        /// </summary>
        public static string BirthCertificateSerial1 {
            get {
                return ResourceManager.GetString("BirthCertificateSerial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر محل تولد.
        /// </summary>
        public static string BirthPlaceCity {
            get {
                return ResourceManager.GetString("BirthPlaceCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان محل تولد.
        /// </summary>
        public static string BirthPlaceProvince {
            get {
                return ResourceManager.GetString("BirthPlaceProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار بلوکه شده.
        /// </summary>
        public static string BlockBalance {
            get {
                return ResourceManager.GetString("BlockBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ شارژ کارت(ريال ایران).
        /// </summary>
        public static string CardChargeRequestModel_Amount {
            get {
                return ResourceManager.GetString("CardChargeRequestModel_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ شارژ کارت.
        /// </summary>
        public static string CardChargeValue {
            get {
                return ResourceManager.GetString("CardChargeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کارت.
        /// </summary>
        public static string CardDetail {
            get {
                return ResourceManager.GetString("CardDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کارت.
        /// </summary>
        public static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع کارت ها.
        /// </summary>
        public static string CardTypes {
            get {
                return ResourceManager.GetString("CardTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ شارژ(ريال ایران).
        /// </summary>
        public static string ChargeAmount {
            get {
                return ResourceManager.GetString("ChargeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمزد شارژ(%).
        /// </summary>
        public static string ChargeWage {
            get {
                return ResourceManager.GetString("ChargeWage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر محل تولد.
        /// </summary>
        public static string CityOfBirth {
            get {
                return ResourceManager.GetString("CityOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر محل صدور.
        /// </summary>
        public static string CityOfIssue {
            get {
                return ResourceManager.GetString("CityOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام ثبت احوال انجام نشده است.
        /// </summary>
        public static string CivilRegistryNotDone {
            get {
                return ResourceManager.GetString("CivilRegistryNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مشتری.
        /// </summary>
        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصلاح درخواست.
        /// </summary>
        public static string CorrectionRequest {
            get {
                return ResourceManager.GetString("CorrectionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ درخواست.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کننده.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مشتری.
        /// </summary>
        public static string CustomerFName {
            get {
                return ResourceManager.GetString("CustomerFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی مشتری.
        /// </summary>
        public static string CustomerFullName {
            get {
                return ResourceManager.GetString("CustomerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات مشتری(صاحب کارت).
        /// </summary>
        public static string CustomerInfo {
            get {
                return ResourceManager.GetString("CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی مشتری.
        /// </summary>
        public static string CustomerLName {
            get {
                return ResourceManager.GetString("CustomerLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مشتری.
        /// </summary>
        public static string CustomerNumber {
            get {
                return ResourceManager.GetString("CustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cvv.
        /// </summary>
        public static string Cvv {
            get {
                return ResourceManager.GetString("Cvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب محل تحویل(نمایندگی).
        /// </summary>
        public static string DeliveryAgent {
            get {
                return ResourceManager.GetString("DeliveryAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واریز.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاحبان حساب/وضعیت.
        /// </summary>
        public static string DepositOwners {
            get {
                return ResourceManager.GetString("DepositOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت حساب.
        /// </summary>
        public static string DepositStatus {
            get {
                return ResourceManager.GetString("DepositStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند شماره.
        /// </summary>
        public static string DocNumber {
            get {
                return ResourceManager.GetString("DocNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود اکسل استعلام  8 گانه-بصورت گروهی.
        /// </summary>
        public static string DownloadGroupOctetExcel {
            get {
                return ResourceManager.GetString("DownloadGroupOctetExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود اکسل استعلام  8 گانه.
        /// </summary>
        public static string DownloadOctetExcel {
            get {
                return ResourceManager.GetString("DownloadOctetExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات هویتی.
        /// </summary>
        public static string EditIdentityInformation {
            get {
                return ResourceManager.GetString("EditIdentityInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل(نام کاربری).
        /// </summary>
        public static string Email_Username_ {
            get {
                return ResourceManager.GetString("Email(Username)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را فقط با حروف انگلیسی و اعداد وارد کنید.
        /// </summary>
        public static string EnglishAndNumberRegularExpressionMessage {
            get {
                return ResourceManager.GetString("EnglishAndNumberRegularExpressionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را فقط با حروف انگلیسی وارد کنید.
        /// </summary>
        public static string EnglishRegularExpressionMessage {
            get {
                return ResourceManager.GetString("EnglishRegularExpressionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه انقضاء.
        /// </summary>
        public static string ExpireMonth {
            get {
                return ResourceManager.GetString("ExpireMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال انقضاء.
        /// </summary>
        public static string ExpireYear {
            get {
                return ResourceManager.GetString("ExpireYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تسهیلات.
        /// </summary>
        public static string FacilityNumber {
            get {
                return ResourceManager.GetString("FacilityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمزد.
        /// </summary>
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زن.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اول.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید عددی حداکثر دو رقم اعشار باشد.
        /// </summary>
        public static string FloatRegularExpression {
            get {
                return ResourceManager.GetString("FloatRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراموشی کلمه عبور؟.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کارت فعال.
        /// </summary>
        public static string FreeCardCount {
            get {
                return ResourceManager.GetString("FreeCardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ عملیات.
        /// </summary>
        public static string HistoryDate {
            get {
                return ResourceManager.GetString("HistoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع عملیات.
        /// </summary>
        public static string HistoryStatus {
            get {
                return ResourceManager.GetString("HistoryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا.
        /// </summary>
        public static string IBAN {
            get {
                return ResourceManager.GetString("IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات/اسناد هویتی.
        /// </summary>
        public static string IdentityDocuments {
            get {
                return ResourceManager.GetString("IdentityDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر ثبت نام کرده اید،وارد شوید.
        /// </summary>
        public static string IfYouHaveRegisteredLogIn {
            get {
                return ResourceManager.GetString("IfYouHaveRegisteredLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید عددی باشد.
        /// </summary>
        public static string IntegerRegularExpression {
            get {
                return ResourceManager.GetString("IntegerRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا کلمه عبور اشتباه است!.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -تصویر مدرک شغلی را بارگذاری کنید&lt;br/&gt;
        ///-حجم فایل باگذاری شده نباید بیشتر از 1 مگابایت باشد&lt;br/&gt;
        ///-مشخصات روی تصویر باید خوانا باشد.
        /// </summary>
        public static string JobDocument_Description {
            get {
                return ResourceManager.GetString("JobDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر مدرک شغلی.
        /// </summary>
        public static string JobDocumentUploadInfo {
            get {
                return ResourceManager.GetString("JobDocumentUploadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهاد مالی.
        /// </summary>
        public static string Leasing {
            get {
                return ResourceManager.GetString("Leasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سیستم.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری زرین لند.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرد.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت فوق غیرفعال/مسدود می باشد.
        /// </summary>
        public static string MessageCardIsInActive {
            get {
                return ResourceManager.GetString("MessageCardIsInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل تکراری می باشد!.
        /// </summary>
        public static string MessageErrorExistEmail {
            get {
                return ResourceManager.GetString("MessageErrorExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل تکراری می باشد!.
        /// </summary>
        public static string MessageErrorExistMobile {
            get {
                return ResourceManager.GetString("MessageErrorExistMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی تکراری میباشد!.
        /// </summary>
        public static string MessageErrorExistNationalCode {
            get {
                return ResourceManager.GetString("MessageErrorExistNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری تکراری می باشد!.
        /// </summary>
        public static string MessageErrorExistUsername {
            get {
                return ResourceManager.GetString("MessageErrorExistUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات با موفقیت انجام شد.
        /// </summary>
        public static string MessageSuccess {
            get {
                return ResourceManager.GetString("MessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید حداقل {1} و حداکثر {2} حرف/عدد باشد!.
        /// </summary>
        public static string MinMaxLengthValidationMessage {
            get {
                return ResourceManager.GetString("MinMaxLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تراکنش.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه پرداخت.
        /// </summary>
        public static string MonthCountTitle {
            get {
                return ResourceManager.GetString("MonthCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصاویر کارت ملی.
        /// </summary>
        public static string NationalCard {
            get {
                return ResourceManager.GetString("NationalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر پشت کارت ملی.
        /// </summary>
        public static string NationalCardBack {
            get {
                return ResourceManager.GetString("NationalCardBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -تصویر پشت کارت ملی را بارگذاری کنید&lt;br/&gt;
        ///-حجم فایل باگذاری شده نباید بیشتر از 1 مگابایت باشد&lt;br/&gt;
        ///-مشخصات روی تصویر باید خوانا باشد.
        /// </summary>
        public static string NationalCardBack_Info {
            get {
                return ResourceManager.GetString("NationalCardBack_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر روی کارت ملی.
        /// </summary>
        public static string NationalCardFront {
            get {
                return ResourceManager.GetString("NationalCardFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -تصویر روی کارت ملی را بارگذاری کنید&lt;br/&gt;
        ///-حجم فایل باگذاری شده نباید بیشتر از 1 مگابایت باشد&lt;br/&gt;
        ///-تمام مشخصات روی تصویر باید با اطلاعات هویتی که در هنگام ثبت نام وارد کرده اید،یکسان باشد&lt;br/&gt;
        ///-مشخصات روی تصویر باید خوانا باشد.
        /// </summary>
        public static string NationalCardFront_Info {
            get {
                return ResourceManager.GetString("NationalCardFront_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملیت.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری تصاویر کارت ملی.
        /// </summary>
        public static string NationlCardUploadInfo {
            get {
                return ResourceManager.GetString("NationlCardUploadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی برای نمایش وجود ندارد.
        /// </summary>
        public static string NoRows {
            get {
                return ResourceManager.GetString("NoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر اقدام کننده.
        /// </summary>
        public static string OperatorId {
            get {
                return ResourceManager.GetString("OperatorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پاسپورت.
        /// </summary>
        public static string PassportID {
            get {
                return ResourceManager.GetString("PassportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور و تکرار کلمه عبور باید یکسان باشند.
        /// </summary>
        public static string PasswordCompareError {
            get {
                return ResourceManager.GetString("PasswordCompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید حداقل  {2} کاراکتر باشد..
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان پرداخت.
        /// </summary>
        public static string PaymentPeriod {
            get {
                return ResourceManager.GetString("PaymentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را فقط با حروف فارسی وارد کنید.
        /// </summary>
        public static string PersianRegularExpressionMessage {
            get {
                return ResourceManager.GetString("PersianRegularExpressionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات هویتی.
        /// </summary>
        public static string PersonInfo {
            get {
                return ResourceManager.GetString("PersonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل صدور.
        /// </summary>
        public static string PlaceOfIssue {
            get {
                return ResourceManager.GetString("PlaceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت را با فرمت صحیح وارد کنید :.
        /// </summary>
        public static string PleaseInpuCardNumberToInccorectFormat {
            get {
                return ResourceManager.GetString("PleaseInpuCardNumberToInccorectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اسناد خود را برای افزایش اعتبار بارگذاری کنید.
        /// </summary>
        public static string PleaseSelectAttachment {
            get {
                return ResourceManager.GetString("PleaseSelectAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا صبر کنید.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره انتظامی.
        /// </summary>
        public static string PoliceNumber {
            get {
                return ResourceManager.GetString("PoliceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبل.
        /// </summary>
        public static string Prev {
            get {
                return ResourceManager.GetString("Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فراگیر(اختصاصی).
        /// </summary>
        public static string PrivateId {
            get {
                return ResourceManager.GetString("PrivateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فراگیر باید عددی بین 8 تا 12 رقمی باشد.
        /// </summary>
        public static string PrivateIdMinMaxLength {
            get {
                return ResourceManager.GetString("PrivateIdMinMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فراگیر.
        /// </summary>
        public static string PrivateNumber {
            get {
                return ResourceManager.GetString("PrivateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل من.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان محل تولد.
        /// </summary>
        public static string ProvinceOfBirth {
            get {
                return ResourceManager.GetString("ProvinceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان محل صدور.
        /// </summary>
        public static string ProvinceOfIssue {
            get {
                return ResourceManager.GetString("ProvinceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید عددی بین {1} تا {2} باشد.
        /// </summary>
        public static string RangeValidationMessage {
            get {
                return ResourceManager.GetString("RangeValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار واقعی.
        /// </summary>
        public static string RealBalance {
            get {
                return ResourceManager.GetString("RealBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام کنید!.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت درخواست.
        /// </summary>
        public static string RegisterRequest {
            get {
                return ResourceManager.GetString("RegisterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام خریدار/فروشنده.
        /// </summary>
        public static string RegisterSellerBuyer {
            get {
                return ResourceManager.GetString("RegisterSellerBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را با فرمت صحیح وارد کنید.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا بخاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی.
        /// </summary>
        public static string RequestAmount {
            get {
                return ResourceManager.GetString("RequestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ درخواست.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست تسهیلات(اعتبار).
        /// </summary>
        public static string RequestFacility {
            get {
                return ResourceManager.GetString("RequestFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت درخواست جدید.
        /// </summary>
        public static string RequestFacilityAdd {
            get {
                return ResourceManager.GetString("RequestFacilityAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست درخواست ها.
        /// </summary>
        public static string RequestFacilityList {
            get {
                return ResourceManager.GetString("RequestFacilityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه در خواست.
        /// </summary>
        public static string RequestHistory {
            get {
                return ResourceManager.GetString("RequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست درخواست ها.
        /// </summary>
        public static string RequestList {
            get {
                return ResourceManager.GetString("RequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت درخواست.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع درخواست.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تصویر اجاره نامه یا سند مالکیت محل سکونت را بارگذاری کنید!.
        /// </summary>
        public static string RequiredMessageAddressDocument {
            get {
                return ResourceManager.GetString("RequiredMessageAddressDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تصویر توضیحات شناسنامه را بارگذاری کنید!.
        /// </summary>
        public static string RequiredMessageBirthCertificateDescription {
            get {
                return ResourceManager.GetString("RequiredMessageBirthCertificateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تصویر صفحه اول شناسنامه را باگذاری کنید!.
        /// </summary>
        public static string RequiredMessageBirthCertificatePage1 {
            get {
                return ResourceManager.GetString("RequiredMessageBirthCertificatePage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تصویر صفحه دوم شناسنامه را باگذاری کنید!.
        /// </summary>
        public static string RequiredMessageBirthCertificatePage2 {
            get {
                return ResourceManager.GetString("RequiredMessageBirthCertificatePage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تصویر مدرک شغلی را بارگذاری کنید!.
        /// </summary>
        public static string RequiredMessageJobDocument {
            get {
                return ResourceManager.GetString("RequiredMessageJobDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تصویر پشت کارت ملی را بارگذاری کنید!.
        /// </summary>
        public static string RequiredMessageNationalCardBack {
            get {
                return ResourceManager.GetString("RequiredMessageNationalCardBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تصویر روی کارت ملی را بارگذاری کنید!.
        /// </summary>
        public static string RequiredMessageNationalCardFront {
            get {
                return ResourceManager.GetString("RequiredMessageNationalCardFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} اجباری است!.
        /// </summary>
        public static string RequiredValidationMessage {
            get {
                return ResourceManager.GetString("RequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ريال.
        /// </summary>
        public static string Rial {
            get {
                return ResourceManager.GetString("Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی براساس شماره کارت.
        /// </summary>
        public static string Search_to_CardNumber {
            get {
                return ResourceManager.GetString("Search_to_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز دوم.
        /// </summary>
        public static string SecondPassword {
            get {
                return ResourceManager.GetString("SecondPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک را انتخاب کنید.
        /// </summary>
        public static string SelectBank {
            get {
                return ResourceManager.GetString("SelectBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر محل سکونت را انتخاب کنید.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر محل تولد را انتخاب کنید.
        /// </summary>
        public static string SelectCityOfBirth {
            get {
                return ResourceManager.GetString("SelectCityOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر محل صدور شناسنامه را انتخاب کنید.
        /// </summary>
        public static string SelectCityOfIssue {
            get {
                return ResourceManager.GetString("SelectCityOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت را انتخاب کنید.
        /// </summary>
        public static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهاد مالی را انتخاب کنید.
        /// </summary>
        public static string SelectLeasing {
            get {
                return ResourceManager.GetString("SelectLeasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملیت را انتخاب کنید.
        /// </summary>
        public static string SelectNationality {
            get {
                return ResourceManager.GetString("SelectNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان پرداخت را انتخاب کنید.
        /// </summary>
        public static string SelectPaymentPeriod {
            get {
                return ResourceManager.GetString("SelectPaymentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان محل سکونت را انتخاب کنید.
        /// </summary>
        public static string SelectProvince {
            get {
                return ResourceManager.GetString("SelectProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان محل تولد را انتخاب کنید.
        /// </summary>
        public static string SelectProvinceOfBirth {
            get {
                return ResourceManager.GetString("SelectProvinceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان محل صدرو شناسنامه تولد را انتخاب کنید.
        /// </summary>
        public static string SelectProvinceOfIssue {
            get {
                return ResourceManager.GetString("SelectProvinceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از سیستم.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زرین لند.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شناسنامه.
        /// </summary>
        public static string SSID {
            get {
                return ResourceManager.GetString("SSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات مدیر.
        /// </summary>
        public static string StatusDescription {
            get {
                return ResourceManager.GetString("StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ بروزرسانی وضعیت.
        /// </summary>
        public static string StatusUpdate {
            get {
                return ResourceManager.GetString("StatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} حداکثر میتواند {1}  کاراکتر باشد.
        /// </summary>
        public static string StringLengthMessage {
            get {
                return ResourceManager.GetString("StringLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ريال.
        /// </summary>
        public static string Toman {
            get {
                return ResourceManager.GetString("Toman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کل رکوردها.
        /// </summary>
        public static string TotalRowCount {
            get {
                return ResourceManager.GetString("TotalRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ-ساعت تراکنش.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش ها.
        /// </summary>
        public static string TransactionList {
            get {
                return ResourceManager.GetString("TransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تراکنش.
        /// </summary>
        public static string TransactionTypeEnum {
            get {
                return ResourceManager.GetString("TransactionTypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی نامشخص رخ داده است.
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری نتیجه اکسل استعلام 8 گانه - گروهی.
        /// </summary>
        public static string UploadGroupOctetExcelResult {
            get {
                return ResourceManager.GetString("UploadGroupOctetExcelResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری مدارک هویتی.
        /// </summary>
        public static string UploadIdentityDocuments {
            get {
                return ResourceManager.GetString("UploadIdentityDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری نتیجه اکسل استعلام 8 گانه .
        /// </summary>
        public static string UploadOctetExcelResult {
            get {
                return ResourceManager.GetString("UploadOctetExcelResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست نمایندگان/کاربران.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران سیستم.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمزد.
        /// </summary>
        public static string Wage {
            get {
                return ResourceManager.GetString("Wage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزایش اعتبار.
        /// </summary>
        public static string WalletCharge {
            get {
                return ResourceManager.GetString("WalletCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ افزایش اعتبار(ريال ایران).
        /// </summary>
        public static string WalletChargeAmount {
            get {
                return ResourceManager.GetString("WalletChargeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست های افزایش اعتبار.
        /// </summary>
        public static string WalletChargeList {
            get {
                return ResourceManager.GetString("WalletChargeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت درخواست افزایش اعتبار.
        /// </summary>
        public static string WalletChargeRegister {
            get {
                return ResourceManager.GetString("WalletChargeRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برداشت.
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه زرین پال.
        /// </summary>
        public static string ZP_Id {
            get {
                return ResourceManager.GetString("ZP_Id", resourceCulture);
            }
        }
    }
}
